title: NerdCuentos
description: Bienvenidos sean todos al podcast de historias curiosas, tecnología, juegos y un montón de ñoñerías.
baseurl: ""
url: "http://www.nerdcuentos.com"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed settings
title:          NerdCuentos
email:          nerdcuentos@gmail.com
description:    "Este es un podcast semanal en el que Francisco Fierro y Macarena Millapán les contarán una historia diferente e interesante."
#subtitle:       "."
url:            http://www.nerdcuentos.com/
language:       en-us
author:         NerdCuentos
copyright:      "CC BY 4.0"

feed:
  collections:
    episodes:
      path: "/episodes.xml"

collections:
  episodes:
